// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MarvinPaktolus.Models
{
    public partial class MarvinVelasquezContext : DbContext
    {
        public MarvinVelasquezContext()
        {
        }

        public MarvinVelasquezContext(DbContextOptions<MarvinVelasquezContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Hobbies> Hobbies { get; set; }
        public virtual DbSet<StudentHobbies> StudentHobbies { get; set; }
        public virtual DbSet<Students> Students { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Hobbies>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<StudentHobbies>(entity =>
            {
                entity.HasOne(d => d.Hobbie)
                    .WithMany(p => p.StudentHobbies)
                    .HasForeignKey(d => d.HobbieId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__StudentHo__Hobbi__3C69FB99");

                entity.HasOne(d => d.Student)
                    .WithMany(p => p.StudentHobbies)
                    .HasForeignKey(d => d.StudentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__StudentHo__Stude__3B75D760");
            });

            modelBuilder.Entity<Students>(entity =>
            {
                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Phone)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Zip)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}