// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MarvinPaktolus.Models
{
    public partial class Students
    {
        public Students()
        {
            StudentHobbies = new HashSet<StudentHobbies>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Zip { get; set; }

        public virtual ICollection<StudentHobbies> StudentHobbies { get; set; }
    }
}